version: "3"
services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
